services:
  db:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: kc_root_password
      MYSQL_DATABASE: mboard
      MYSQL_USER: akana
      MYSQL_PASSWORD: water3366
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: